steps:
  # Step 1: Build Docker image (use the predefined:latest variable)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dauntless-tube-441623-h6/springboot-app:latest', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dauntless-tube-441623-h6/springboot-app:latest']

  # Step 3: Create Google Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying image: gcr.io/dauntless-tube-441623-h6/springboot-app:latest"
        echo '{
          "images": [
            {
              "image": "gcr.io/dauntless-tube-441623-h6/springboot-app:latest"
            }
          ]
        }' > build-artifacts.json

        cat build-artifacts.json
        gcloud deploy releases create springboot-latest \
          --delivery-pipeline=springboot-delivery-pipeline \
          --region=${_REGION} \
          --build-artifacts=build-artifacts.json \
          --description="Triggered by Cloud Build"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: us-west2
