steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dauntless-tube-441623-h6/springboot-app:${_SHORTSHA}', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dauntless-tube-441623-h6/springboot-app:${_SHORTSHA}']

  # Step 3: Create Google Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo '{"images":[{"image":"gcr.io/dauntless-tube-441623-h6/springboot-app:${_SHORTSHA}"}]}' > build_artifacts.json
        gcloud deploy releases create springboot-$BUILD_ID \
          --delivery-pipeline=springboot-delivery-pipeline \
          --region=${_REGION} \
          --build-artifacts=build_artifacts.json \
          --annotations=commitSha=${_COMMITSHA} \
          --description="Triggered by Cloud Build"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: us-west2
  _SHORTSHA: "$(git rev-parse --short HEAD)"  # Ensure that SHORT_SHA is correctly set
  _COMMITSHA: "$(git rev-parse HEAD)"  # Full commit hash
