apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: my-app
build:
  artifacts:
    - image: gcr.io/dauntless-tube-441623-h6/springboot-app  # Image name
  tagPolicy:
    sha256: {}  # Use SHA-256 digest-based tagging for reproducible builds
deploy:
  kubectl:
    manifests:
      - deploy/deployment.yaml
      - deploy/service.yaml
      - deploy/ingress.yaml
    flags:
      apply: ["--prune=false"]
profiles:
  - name: target-1
    deploy:
      kubectl:
        manifests:
          - deploy/deployment.yaml
          - deploy/service.yaml
          - deploy/ingress.yaml
